using System;
using System.Xml.Serialization;

namespace FzCommon.ExternalModels.NwrfcForecast
{
    // These classes were autogenerated from the source XML.
    public class HydroMetForecastValue
    {
        [XmlElement("creationDateTime")]
        public DateTime CreationDateTime    { get; set; }
        [XmlElement("dataDateTime")]
        public DateTime DataDateTime        { get; set; }
        [XmlElement("stage")]
        public double Stage                 { get; set; }
        [XmlElement("discharge")]
        public double Discharge              { get; set; }
    }

    public class HydroMetSite
    {
        [XmlAttribute("id")]
        public string SiteId        { get; set; }
        [XmlElement("description")]
        public string Description   { get; set; }
        [XmlElement("county")]
        public string County        { get; set; }
        [XmlElement("state")]
        public string State         { get; set; }
        [XmlElement("elevation")]
        public double? Elevation     { get; set; }
        [XmlElement("latitude")]
        public double? Latitude      { get; set; }
        [XmlElement("longitude")]
        public double? Longitude     { get; set; }
        [XmlElement("bankfullStage")]
        public double? BankFullStage { get; set; }
        [XmlElement("floodStage")]
        public double? FloodStage    { get; set; }
        [XmlArray(ElementName = "forecastData")]
        [XmlArrayItem("forecastValue", typeof(HydroMetForecastValue), IsNullable=false)]
        public HydroMetForecastValue[] ForecastData { get; set; }
    }

    [XmlRoot(Namespace="/xml/schemas/2004/03/hydromet_data", IsNullable=false)]
    public class HydroMetData
    {
        [XmlElement("SiteData")]
        public HydroMetSite Site    { get; set; }
    }
}

